version: '3.8'

services:
  app:
    build: .
    container_name: mcp_server_dev
    # THIS IS THE CRUCIAL LINE. Ensure it is "npm run dev".
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    stdin_open: true

# Optional but Recommended: If you want to test against a real database like PostgreSQL
# you can easily spin one up here.
#  db:
#    image: postgres:14-alpine
#    container_name: my_postgres_db
#    environment:
#      - POSTGRES_USER=myuser
#      - POSTGRES_PASSWORD=mypassword
#      - POSTGRES_DB=mydb
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

# volumes:
#  postgres_data: